version: '3.8'

services:
  files-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DEBUG=True
      - MAX_FILE_SIZE=8388608
      - BASE_URL=https://euwest.api.elasticpath.com
      # Authentication - In production, don't disable auth and use real credentials
      - DISABLE_AUTH=True
      - CLIENT_ID=your-client-id
      - CLIENT_SECRET=your-client-secret
    restart: unless-stopped
